import { test } from 'node:test';
import assert from 'node:assert/strict';
import { encode } from 'fast-png';
import { reportsD1 } from './support/sqlite-d1.ts';
import { createReport, minimizeAfter } from '../src/reports/create.ts';
import { CURRENT_REPORT_TERMS } from '../src/reports/terms.ts';
import { attachEvidencePhoto, cleanupEvidencePhotos, moderateEvidencePhoto, photoEvidenceStrength } from '../src/reports/photos.ts';
import { MemoryEvidencePhotoStorage } from '../src/reports/photo-storage.ts';
import { applyReportRetention } from '../src/reports/retention.ts';
const now=new Date('2026-10-01T00:00:00Z'); const hash='a'.repeat(64);
async function setup(){ const db=reportsD1(); const storage=new MemoryEvidencePhotoStorage(); const report=await createReport(db,{schemaVersion:1,type:'exists',spotId:'sp_01V64NN31G72E5KJJ5W22W1A1J',installId:'8f1c4d2e-0a3b-4c5d-8e9f-0a1b2c3d4e5f',acceptedTermsVersion:CURRENT_REPORT_TERMS.version},{now,attestationStatus:'verified',submitterHash:hash}); return {db,storage,input:{reportId:report.reportId,submitterHash:hash,idempotencyKey:crypto.randomUUID(),acceptedTermsVersion:CURRENT_REPORT_TERMS.version,bytes:encode({width:1,height:1,channels:4,data:new Uint8Array([1,2,3,255])}),mediaType:'image/png'},opts:{now,enabled:true,photoTermsCovered:()=>true}}; }
test('feature and rights fail closed before storage; ownership/missing report enforced',async()=>{const x=await setup(); for(const [input,opts,code] of [[x.input,{now},'photoEvidenceDisabled'],[x.input,{now,enabled:true},'photoConsentRequired'],[{...x.input,submitterHash:'b'.repeat(64)},x.opts,'photoUnauthorized'],[{...x.input,reportId:'unknown'},x.opts,'reportNotFound']] as const){await assert.rejects(attachEvidencePhoto(x.db,x.storage,input,opts),(e:any)=>e.code===code);} assert.equal(x.storage.objects.size,0);});
test('duplicate images and retries are deterministic and consume guards',async()=>{const x=await setup(); const a=await attachEvidencePhoto(x.db,x.storage,x.input,x.opts); const b=await attachEvidencePhoto(x.db,x.storage,{...x.input,idempotencyKey:crypto.randomUUID()},x.opts); assert.deepEqual(a,b); await attachEvidencePhoto(x.db,x.storage,x.input,{...x.opts,guards:[x.db.prepare("INSERT INTO community_photo_deletions VALUES('guard','now')")]}); assert.equal(x.storage.objects.size,1); assert.ok(x.db.raw.prepare("SELECT * FROM community_photo_deletions WHERE storage_key='guard'").get()); await assert.rejects(attachEvidencePhoto(x.db,x.storage,{...x.input,bytes:encode({width:1,height:1,channels:4,data:new Uint8Array([2,3,4,255])})},x.opts),(e:any)=>e.code==='photoIdempotencyConflict');});
test('moderation is explicit and never proves permission',async()=>{const x=await setup();const p=await attachEvidencePhoto(x.db,x.storage,x.input,x.opts); assert.deepEqual(await photoEvidenceStrength(x.db,x.input.reportId,now),{approvedPhotos:0,permissionToSmoke:false}); await moderateEvidencePhoto(x.db,p.photoId,'approved',{now,decidedBy:'reviewer',reason:'usableEvidence'}); assert.deepEqual(await photoEvidenceStrength(x.db,x.input.reportId,now),{approvedPhotos:1,permissionToSmoke:false}); await assert.rejects(moderateEvidencePhoto(x.db,p.photoId,'rejected',{now,decidedBy:'reviewer',reason:'privacyRisk'}));});
test('attachment count is capped at three distinct derivatives',async()=>{const x=await setup();for(let i=0;i<3;i++)await attachEvidencePhoto(x.db,x.storage,{...x.input,idempotencyKey:crypto.randomUUID(),bytes:encode({width:1,height:1,channels:4,data:new Uint8Array([i,1,1,255])})},x.opts);await assert.rejects(attachEvidencePhoto(x.db,x.storage,{...x.input,idempotencyKey:crypto.randomUUID(),bytes:encode({width:1,height:1,channels:4,data:new Uint8Array([99,1,1,255])})},x.opts),(e:any)=>e.code==='photoAttachmentLimit');assert.equal(x.storage.objects.size,3);});
test('retention deletes objects at report deadline; deletion tombstones survive report removal',async()=>{const x=await setup();await attachEvidencePhoto(x.db,x.storage,x.input,x.opts);await applyReportRetention(x.db,{now:minimizeAfter(now),photoStorage:x.storage});assert.equal(x.storage.objects.size,0);assert.equal(x.db.raw.prepare('SELECT count(*) n FROM community_evidence_photos').get()?.n,0);const y=await setup();await attachEvidencePhoto(y.db,y.storage,y.input,y.opts); y.db.raw.prepare('DELETE FROM reports WHERE report_id=?').run(y.input.reportId);assert.equal(y.db.raw.prepare('SELECT count(*) n FROM community_photo_deletions').get()?.n,1);await cleanupEvidencePhotos(y.db,y.storage,{now});assert.equal(y.storage.objects.size,0);});
test('failed partial put has durable orphan cleanup and supports retry',async()=>{const x=await setup();let fail=true;const original=x.storage.put.bind(x.storage);x.storage.put=async(...args)=>{await original(...args);if(fail)throw Error('storage unavailable');};await assert.rejects(attachEvidencePhoto(x.db,x.storage,x.input,x.opts));fail=false;await attachEvidencePhoto(x.db,x.storage,x.input,x.opts);assert.equal(x.storage.objects.size,1);const y=await setup();y.storage.put=async(...args)=>{await MemoryEvidencePhotoStorage.prototype.put.apply(y.storage,args);throw Error('storage unavailable');};await assert.rejects(attachEvidencePhoto(y.db,y.storage,y.input,y.opts));await cleanupEvidencePhotos(y.db,y.storage,{now:new Date(now.getTime()+16*60_000)});assert.equal(y.storage.objects.size,0);});
test('cleanup retains deletion work when storage fails and fences delayed puts',async()=>{const x=await setup();await attachEvidencePhoto(x.db,x.storage,x.input,x.opts);const [key,obj]=[...x.storage.objects][0];const remove=x.storage.delete.bind(x.storage);x.storage.delete=async()=>{throw Error('delete offline');};await assert.rejects(cleanupEvidencePhotos(x.db,x.storage,{now:minimizeAfter(now)}));assert.equal(x.db.raw.prepare('SELECT count(*) n FROM community_photo_deletions').get()?.n,1);x.storage.delete=remove;await cleanupEvidencePhotos(x.db,x.storage,{now:minimizeAfter(now)});await assert.rejects(x.storage.put(key,obj.bytes,obj.metadata),/permanently deleted/);});
test('concurrent identical requests succeed; conflicting idempotency races cannot attach twice',async()=>{const x=await setup();const same=await Promise.all([attachEvidencePhoto(x.db,x.storage,x.input,x.opts),attachEvidencePhoto(x.db,x.storage,x.input,x.opts)]);assert.deepEqual(same[0],same[1]);const y=await setup();const replies=await Promise.allSettled([attachEvidencePhoto(y.db,y.storage,y.input,y.opts),attachEvidencePhoto(y.db,y.storage,{...y.input,bytes:encode({width:1,height:1,channels:4,data:new Uint8Array([9,1,1,255])})},y.opts)]);assert.equal(replies.filter(r=>r.status==='fulfilled').length,1);assert.equal(y.db.raw.prepare('SELECT count(*) n FROM community_evidence_photos').get()?.n,1);});

test('privacy rejection queues derivative deletion immediately and approval strength expires',async()=>{const x=await setup();const p=await attachEvidencePhoto(x.db,x.storage,x.input,x.opts);await moderateEvidencePhoto(x.db,p.photoId,'rejected',{now,decidedBy:'reviewer',reason:'privacyRisk'});assert.equal(x.db.raw.prepare('SELECT count(*) n FROM community_photo_deletions').get()?.n,1);await cleanupEvidencePhotos(x.db,x.storage,{now});assert.equal(x.storage.objects.size,0);const y=await setup();const q=await attachEvidencePhoto(y.db,y.storage,y.input,y.opts);await moderateEvidencePhoto(y.db,q.photoId,'approved',{now,decidedBy:'reviewer',reason:'usableEvidence'});assert.deepEqual(await photoEvidenceStrength(y.db,y.input.reportId,minimizeAfter(now)),{approvedPhotos:0,permissionToSmoke:false});});

test('expired upload retains idempotency hash binding until report redaction',async()=>{const x=await setup();const put=x.storage.put.bind(x.storage);x.storage.put=async()=>{throw Error('offline');};await assert.rejects(attachEvidencePhoto(x.db,x.storage,x.input,x.opts));const later=new Date(now.getTime()+16*60_000);await cleanupEvidencePhotos(x.db,x.storage,{now:later});x.storage.put=put;await assert.rejects(attachEvidencePhoto(x.db,x.storage,{...x.input,bytes:encode({width:1,height:1,channels:4,data:new Uint8Array([9,1,1,255])})},{...x.opts,now:later}),(e:any)=>e.code==='photoIdempotencyConflict');await assert.rejects(attachEvidencePhoto(x.db,x.storage,x.input,{...x.opts,now:later}),(e:any)=>e.code==='photoExpired');await attachEvidencePhoto(x.db,x.storage,{...x.input,idempotencyKey:crypto.randomUUID()},{...x.opts,now:later});await applyReportRetention(x.db,{now:minimizeAfter(now),photoStorage:x.storage});assert.equal(x.db.raw.prepare('SELECT count(*) n FROM community_photo_requests').get()?.n,0);});
